import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'drag_drop': 'Drag n Drop or Pick an Image',
          'paste_message': 'Paste Your Message Here',
          'input_message': 'Input Message',
          'submit': 'Submit',
          'response_message': 'Response Message',
          'response_of_input': 'Response Of Your Input',
          'copied': 'Copied: Response copied to clipboard',
          'generate_first_message': 'First Message',
          'need_assistance': 'AI Assistant',
          'ice_breaker': 'Break the silence',
          'random_response': 'Randomly Generated Response',
          'response': 'Response',
          'random_generator': 'Random Generator',
          'privacy_policy_error': 'Could not open Privacy Policy link',
          'privacy_policy': 'Privacy Policy',
          'play_store_error': 'Could not open the Play Store link',
          'app_rating': 'App Rating',
          'google_form_error': 'Could not open Google Form',
          'delete_data_request': 'Delete Data Request',
          'vip': 'VIP',
          'language': 'Language',
          'no_internet': 'No Internet Connection',
          'connection_lost':
              'Your connection has been lost. Please check your internet connection and try again.',
          'okay': 'Okay',
          'retry': 'Retry',
          'welcome_to_chat_assistant': 'Welcome to Chat Assistant',
          'enter_your_age': 'Enter your age',
          'woo_rizz': 'Woo Rizz!',
          'yours_age': "Your's age",
          'select_gender': 'Select Gender',
          'select_language': 'Select Language',
          'lets_start_messaging': "Let's Start Messaging",
          'ai_assistant_rizz': 'AI Assistant Rizz.',
          'current_language': 'Current Language:',
          'english': 'English',
          'arabic': 'Arabic',
          'hindi': 'Hindi',
          'spanish': 'Spanish',
          'german': 'German',
          'french': 'French',
          'russian': 'Russian',
          'portuguese': 'Portuguese',
          'turkish': 'Turkish',
          'greek': 'Greek',
          'dutch': 'Dutch',
          'italian': 'Italian',
          'chinese': 'Chinese',
          'unknown': 'Unknown',
          'or': 'or',
          'male': 'Male',
          'female': 'Female',
          'other': 'Other',
          'language_selected': '{languageName} selected',
          'language_changed_to': 'Language changed to {languageChangedto}',
          'woo_rizz_premium_subscriptions': '✨Woo Rizz Premium Subscriptions',
          'rizz_subscription_catalog': "Rizz's Subscription Catalog",
          'woo_rizz_offering_subscriptions':
              'Woo Rizz offering a variety of subscriptions. Buy according to your choice and get rid of the ads.',
        },
        'ar': {
          // Arabic translations

    "drag_drop": "اسحب وأسقط أو اختر صورة",
    "paste_message": "الصق رسالتك هنا",
    "input_message": "إدخال الرسالة",
    "submit": "إرسال",
    "response_message": "رسالة الرد",
    "response_of_input": "رد على إدخالك",
    "copied": "تم النسخ: تم نسخ الرد إلى الحافظة",
    "generate_first_message": "الرسالة الأولى",
    "need_assistance": "	مساعد الذكاء الاصطناعي",
    "ice_breaker": "اكسر الصمت",
    "random_response": "رد عشوائي تم إنشاؤه",
    "response": "رد",
    "random_generator": "مولد عشوائي",
    "privacy_policy_error": "تعذر فتح رابط سياسة الخصوصية",
    "privacy_policy": "سياسة الخصوصية",
    "play_store_error": "تعذر فتح رابط متجر Play",
    "app_rating": "تقييم التطبيق",
    "google_form_error": "تعذر فتح نموذج Google",
    "delete_data_request": "طلب حذف البيانات",
    "vip": "VIP",
    "language": "اللغة",
    "no_internet": "لا يوجد اتصال بالإنترنت",
    "connection_lost": "تم فقد الاتصال. يرجى التحقق من اتصالك بالإنترنت وحاول مرة أخرى.",
    "okay": "حسنًا",
    "retry": "أعد المحاولة",
    "welcome_to_chat_assistant": "مرحبًا بك في مساعد الدردشة",
    "enter_your_age": "أدخل عمرك",
    "woo_rizz": "وو ريز!",
    "yours_age": "عمرك",
    "select_gender": "اختر الجنس",
    "select_language": "اختر اللغة",
    "lets_start_messaging": "لنبدأ المراسلة",
    "ai_assistant_rizz": "مساعد الذكاء الاصطناعي ريز.",
    "current_language": "اللغة الحالية:",
    "english": "الإنجليزية",
    "arabic": "العربية",
    "hindi": "الهندية",
    "spanish": "الإسبانية",
    "german": "الألمانية",
    "french": "الفرنسية",
    "russian": "الروسية",
    "portuguese": "البرتغالية",
    "turkish": "التركية",
    "greek": "اليونانية",
    "dutch": "الهولندية",
    "italian": "الإيطالية",
    "chinese": "الصينية",
    "unknown": "غير معروف",

    "or": "أو",
  "male": "ذكر",
  "female": "أنثى",
  "other": "آخر",
  "language_selected": "تم اختيار {languageName}",
  "language_changed_to": "تم تغيير اللغة إلى {languageChangedto}",

  "woo_rizz_premium_subscriptions": "✨اشتراكات وو ريز بريميوم",
  "rizz_subscription_catalog": "كتالوج اشتراكات ريز",
  "woo_rizz_offering_subscriptions": "وو ريز تقدم مجموعة متنوعة من الاشتراكات. اختر ما يناسبك وتخلص من الإعلانات."


        },
        'hi': {
          // Hindi translations
          
    "drag_drop": "इमेज खींचें और छोड़ें या चुनें",
    "paste_message": "अपना संदेश यहाँ पेस्ट करें",
    "input_message": "संदेश दर्ज करें",
    "submit": "सबमिट करें",
    "response_message": "प्रतिक्रिया संदेश",
    "response_of_input": "आपके इनपुट की प्रतिक्रिया",
    "copied": "कॉपी किया गया: प्रतिक्रिया क्लिपबोर्ड में कॉपी हो गई",
    "generate_first_message": "पहला संदेश",
    "need_assistance": "एआई सहायक",
    "ice_breaker": "मौन तोड़ो",
    "random_response": "रैंडमली जनरेटेड प्रतिक्रिया",
    "response": "प्रतिक्रिया",
    "random_generator": "रैंडम जनरेटर",
    "privacy_policy_error": "गोपनीयता नीति लिंक नहीं खोल सका",
    "privacy_policy": "गोपनीयता नीति",
    "play_store_error": "प्ले स्टोर लिंक नहीं खोल सका",
    "app_rating": "ऐप रेटिंग",
    "google_form_error": "गूगल फॉर्म नहीं खोल सका",
    "delete_data_request": "डेटा हटाने का अनुरोध",
    "vip": "वीआईपी",
    "language": "भाषा",
    "no_internet": "कोई इंटरनेट कनेक्शन नहीं",
    "connection_lost": "आपका कनेक्शन खो गया है। कृपया अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।",
    "okay": "ठीक है",
    "retry": "पुनः प्रयास करें",
    "welcome_to_chat_assistant": "चैट सहायक में आपका स्वागत है",
    "enter_your_age": "अपनी उम्र दर्ज करें",
    "woo_rizz": "वाह रिज़!",
    "yours_age": "आपकी उम्र",
    "select_gender": "लिंग चुनें",
    "select_language": "भाषा चुनें",
    "lets_start_messaging": "आइए संदेश भेजना शुरू करें",
    "ai_assistant_rizz": "एआई सहायक रिज़।",
    "current_language": "वर्तमान भाषा:",
    "english": "अंग्रेज़ी",
    "arabic": "अरबी",
    "hindi": "हिंदी",
    "spanish": "स्पेनिश",
    "german": "जर्मन",
    "french": "फ्रेंच",
    "russian": "रूसी",
    "portuguese": "पुर्तगाली",
    "turkish": "तुर्की",
    "greek": "ग्रीक",
    "dutch": "डच",
    "italian": "इतालवी",
    "chinese": "चीनी",
    "unknown": "अज्ञात",

    "or": "या",
  "male": "पुरुष",
  "female": "महिला",
  "other": "अन्य",
  "language_selected": "{languageName} चयनित",
  "language_changed_to": "भाषा {languageChangedto} में बदल गई",

  "woo_rizz_premium_subscriptions": "✨वू रिज़ प्रीमियम सदस्यताएँ",
  "rizz_subscription_catalog": "रिज़ की सदस्यता सूची",
  "woo_rizz_offering_subscriptions": "वू रिज़ विभिन्न सदस्यताएँ प्रदान करता है। अपनी पसंद के अनुसार खरीदें और विज्ञापनों से छुटकारा पाएं।"



        },
        'es': {
          // Spanish translations
          
    "drag_drop": "Arrastra y suelta o elige una imagen",
    "paste_message": "Pega tu mensaje aquí",
    "input_message": "Mensaje de entrada",
    "submit": "Enviar",
    "response_message": "Mensaje de respuesta",
    "response_of_input": "Respuesta de tu entrada",
    "copied": "Copiado: Respuesta copiada al portapapeles",
    "generate_first_message": "Primer mensaje",
    "need_assistance": "Asistente de IA",
    "ice_breaker": "Rompe el silencio",
    "random_response": "Respuesta generada aleatoriamente",
    "response": "Respuesta",
    "random_generator": "Generador aleatorio",
    "privacy_policy_error": "No se pudo abrir el enlace de la política de privacidad",
    "privacy_policy": "Política de privacidad",
    "play_store_error": "No se pudo abrir el enlace de Play Store",
    "app_rating": "Calificación de la aplicación",
    "google_form_error": "No se pudo abrir el formulario de Google",
    "delete_data_request": "Solicitud de eliminación de datos",
    "vip": "VIP",
    "language": "Idioma",
    "no_internet": "Sin conexión a internet",
    "connection_lost": "Se perdió tu conexión. Por favor, verifica tu conexión a internet y vuelve a intentarlo.",
    "okay": "De acuerdo",
    "retry": "Reintentar",
    "welcome_to_chat_assistant": "Bienvenido al asistente de chat",
    "enter_your_age": "Introduce tu edad",
    "woo_rizz": "¡Woo Rizz!",
    "yours_age": "Tu edad",
    "select_gender": "Selecciona género",
    "select_language": "Selecciona idioma",
    "lets_start_messaging": "Comencemos a enviar mensajes",
    "ai_assistant_rizz": "Asistente de IA Rizz.",
    "current_language": "Idioma actual:",
    "english": "Inglés",
    "arabic": "Árabe",
    "hindi": "Hindi",
    "spanish": "Español",
    "german": "Alemán",
    "french": "Francés",
    "russian": "Ruso",
    "portuguese": "Portugués",
    "turkish": "Turco",
    "greek": "Griego",
    "dutch": "Holandés",
    "italian": "Italiano",
    "chinese": "Chino",
    "unknown": "Desconocido",

    "or": "o",
  "male": "Masculino",
  "female": "Femenino",
  "other": "Otro",
  "language_selected": "{languageName} seleccionado",
  "language_changed_to": "Idioma cambiado a {languageChangedto}",


  "woo_rizz_premium_subscriptions": "✨Suscripciones premium de Woo Rizz",
  "rizz_subscription_catalog": "Catálogo de suscripciones de Rizz",
  "woo_rizz_offering_subscriptions": "Woo Rizz ofrece una variedad de suscripciones. Compra según tu elección y despídete de los anuncios."



        },
        'de': {
          // German translations
          
    "drag_drop": "Ziehen und Ablegen oder ein Bild auswählen",
    "paste_message": "Füge deine Nachricht hier ein",
    "input_message": "Nachricht eingeben",
    "submit": "Senden",
    "response_message": "Antwortnachricht",
    "response_of_input": "Antwort auf deine Eingabe",
    "copied": "Kopiert: Antwort in die Zwischenablage kopiert",
    "generate_first_message": "Erste Nachricht",
    "need_assistance": "KI-Assistent",
    "ice_breaker": "Brich das Schweigen",
    "random_response": "Zufällig generierte Antwort",
    "response": "Antwort",
    "random_generator": "Zufallsgenerator",
    "privacy_policy_error": "Datenschutzrichtlinie-Link konnte nicht geöffnet werden",
    "privacy_policy": "Datenschutzrichtlinie",
    "play_store_error": "Play Store-Link konnte nicht geöffnet werden",
    "app_rating": "App-Bewertung",
    "google_form_error": "Google-Formular konnte nicht geöffnet werden",
    "delete_data_request": "Datenlöschanfrage",
    "vip": "VIP",
    "language": "Sprache",
    "no_internet": "Keine Internetverbindung",
    "connection_lost": "Deine Verbindung wurde unterbrochen. Bitte überprüfe deine Internetverbindung und versuche es erneut.",
    "okay": "Okay",
    "retry": "Erneut versuchen",
    "welcome_to_chat_assistant": "Willkommen beim Chat-Assistenten",
    "enter_your_age": "Gib dein Alter ein",
    "woo_rizz": "Woo Rizz!",
    "yours_age": "Dein Alter",
    "select_gender": "Geschlecht auswählen",
    "select_language": "Sprache auswählen",
    "lets_start_messaging": "Lass uns mit dem Nachrichten beginnen",
    "ai_assistant_rizz": "KI-Assistent Rizz.",
    "current_language": "Aktuelle Sprache:",
    "english": "Englisch",
    "arabic": "Arabisch",
    "hindi": "Hindi",
    "spanish": "Spanisch",
    "german": "Deutsch",
    "french": "Französisch",
    "russian": "Russisch",
    "portuguese": "Portugiesisch",
    "turkish": "Türkisch",
    "greek": "Griechisch",
    "dutch": "Niederländisch",
    "italian": "Italienisch",
    "chinese": "Chinesisch",
    "unknown": "Unbekannt",

     "or": "oder",
  "male": "Männlich",
  "female": "Weiblich",
  "other": "Andere",
  "language_selected": "{languageName} ausgewählt",
  "language_changed_to": "Sprache geändert zu {languageChangedto}",

  
  "woo_rizz_premium_subscriptions": "✨Woo Rizz Premium-Abonnements",
  "rizz_subscription_catalog": "Rizz's Abonnement-Katalog",
  "woo_rizz_offering_subscriptions": "Woo Rizz bietet eine Vielzahl von Abonnements an. Wählen Sie nach Ihren Wünschen und entfernen Sie die Werbung."



        },
        'fr': {
          // French translations
          
    "drag_drop": "Glissez et déposez ou choisissez une image",
    "paste_message": "Collez votre message ici",
    "input_message": "Entrer le message",
    "submit": "Soumettre",
    "response_message": "Message de réponse",
    "response_of_input": "Réponse de votre saisie",
    "copied": "Copié : Réponse copiée dans le presse-papiers",
    "generate_first_message": "Premier message",
    "need_assistance": "Assistant IA",
    "ice_breaker": "Brisez le silence",
    "random_response": "Réponse générée aléatoirement",
    "response": "Réponse",
    "random_generator": "Générateur aléatoire",
    "privacy_policy_error": "Impossible d'ouvrir le lien de la politique de confidentialité",
    "privacy_policy": "Politique de confidentialité",
    "play_store_error": "Impossible d'ouvrir le lien Play Store",
    "app_rating": "Évaluation de l'application",
    "google_form_error": "Impossible d'ouvrir le formulaire Google",
    "delete_data_request": "Demande de suppression de données",
    "vip": "VIP",
    "language": "Langue",
    "no_internet": "Pas de connexion Internet",
    "connection_lost": "Votre connexion a été perdue. Veuillez vérifier votre connexion Internet et réessayer.",
    "okay": "D'accord",
    "retry": "Réessayer",
    "welcome_to_chat_assistant": "Bienvenue dans l'assistant de chat",
    "enter_your_age": "Entrez votre âge",
    "woo_rizz": "Woo Rizz !",
    "yours_age": "Votre âge",
    "select_gender": "Sélectionnez le sexe",
    "select_language": "Sélectionnez la langue",
    "lets_start_messaging": "Commençons à envoyer des messages",
    "ai_assistant_rizz": "Assistant AI Rizz.",
    "current_language": "Langue actuelle :",
    "english": "Anglais",
    "arabic": "Arabe",
    "hindi": "Hindi",
    "spanish": "Espagnol",
    "german": "Allemand",
    "french": "Français",
    "russian": "Russe",
    "portuguese": "Portugais",
    "turkish": "Turc",
    "greek": "Grec",
    "dutch": "Néerlandais",
    "italian": "Italien",
    "chinese": "Chinois",
    "unknown": "Inconnu",

    
     "or": "ou",
  "male": "Homme",
  "female": "Femme",
  "other": "Autre",
  "language_selected": "{languageName} sélectionné",
  "language_changed_to": "Langue changée en {languageChangedto}",


  "woo_rizz_premium_subscriptions": "✨Abonnements Premium Woo Rizz",
  "rizz_subscription_catalog": "Catalogue des abonnements Rizz",
  "woo_rizz_offering_subscriptions": "Woo Rizz propose une variété d'abonnements. Achetez selon votre choix et débarrassez-vous des publicités."





        },
        'ru': {
          // Russian translations
          
    "drag_drop": "Перетащите или выберите изображение",
    "paste_message": "Вставьте ваше сообщение здесь",
    "input_message": "Введите сообщение",
    "submit": "Отправить",
    "response_message": "Сообщение ответа",
    "response_of_input": "Ответ на ваш ввод",
    "copied": "Скопировано: Ответ скопирован в буфер обмена",
    "generate_first_message": "Первое сообщение",
    "need_assistance": "ИИ-ассистент",
    "ice_breaker": "Разбейте тишину",
    "random_response": "Случайно сгенерированный ответ",
    "response": "Ответ",
    "random_generator": "Генератор случайных чисел",
    "privacy_policy_error": "Не удалось открыть ссылку политики конфиденциальности",
    "privacy_policy": "Политика конфиденциальности",
    "play_store_error": "Не удалось открыть ссылку Play Store",
    "app_rating": "Оценка приложения",
    "google_form_error": "Не удалось открыть Google Form",
    "delete_data_request": "Запрос на удаление данных",
    "vip": "VIP",
    "language": "Язык",
    "no_internet": "Нет подключения к Интернету",
    "connection_lost": "Соединение потеряно. Проверьте ваше интернет-соединение и повторите попытку.",
    "okay": "Хорошо",
    "retry": "Повторить",
    "welcome_to_chat_assistant": "Добро пожаловать в Chat Assistant",
    "enter_your_age": "Введите ваш возраст",
    "woo_rizz": "Ву Ризз!",
    "yours_age": "Ваш возраст",
    "select_gender": "Выберите пол",
    "select_language": "Выберите язык",
    "lets_start_messaging": "Давайте начнем общаться",
    "ai_assistant_rizz": "AI Ассистент Ризз.",
    "current_language": "Текущий язык:",
    "english": "Английский",
    "arabic": "Арабский",
    "hindi": "Хинди",
    "spanish": "Испанский",
    "german": "Немецкий",
    "french": "Французский",
    "russian": "Русский",
    "portuguese": "Португальский",
    "turkish": "Турецкий",
    "greek": "Греческий",
    "dutch": "Голландский",
    "italian": "Итальянский",
    "chinese": "Китайский",
    "unknown": "Неизвестный",

     "or": "или",
  "male": "Мужской",
  "female": "Женский",
  "other": "Другое",
  "language_selected": "{languageName} выбрано",
  "language_changed_to": "Язык изменен на {languageChangedto}",


  "woo_rizz_premium_subscriptions": "✨Премиум подписки Woo Rizz",
  "rizz_subscription_catalog": "Каталог подписок Rizz",
  "woo_rizz_offering_subscriptions": "Woo Rizz предлагает разнообразные подписки. Выбирайте по своему вкусу и избавляйтесь от рекламы."



        },
        'pt': {
          // Portuguese translations
          
    "drag_drop": "Arraste e solte ou escolha uma imagem",
    "paste_message": "Cole sua mensagem aqui",
    "input_message": "Mensagem de entrada",
    "submit": "Enviar",
    "response_message": "Mensagem de resposta",
    "response_of_input": "Resposta da sua entrada",
    "copied": "Copiado: Resposta copiada para a área de transferência",
    "generate_first_message": "Primeira mensagem",
    "need_assistance": "Assistente de IA",
    "ice_breaker": "Quebre o silêncio",
    "random_response": "Resposta gerada aleatoriamente",
    "response": "Resposta",
    "random_generator": "Gerador aleatório",
    "privacy_policy_error": "Não foi possível abrir o link da política de privacidade",
    "privacy_policy": "Política de Privacidade",
    "play_store_error": "Não foi possível abrir o link da Play Store",
    "app_rating": "Avaliação do aplicativo",
    "google_form_error": "Não foi possível abrir o formulário do Google",
    "delete_data_request": "Solicitação de exclusão de dados",
    "vip": "VIP",
    "language": "Idioma",
    "no_internet": "Sem conexão com a Internet",
    "connection_lost": "Sua conexão foi perdida. Verifique sua conexão com a Internet e tente novamente.",
    "okay": "Ok",
    "retry": "Tentar novamente",
    "welcome_to_chat_assistant": "Bem-vindo ao Chat Assistant",
    "enter_your_age": "Insira sua idade",
    "woo_rizz": "Woo Rizz!",
    "yours_age": "Sua idade",
    "select_gender": "Selecione o gênero",
    "select_language": "Selecione o idioma",
    "lets_start_messaging": "Vamos começar a enviar mensagens",
    "ai_assistant_rizz": "Assistente AI Rizz.",
    "current_language": "Idioma atual:",

    "english": "Inglês",
    "arabic": "Árabe",
    "hindi": "Hindi",
    "spanish": "Espanhol",
    "german": "Alemão",
    "french": "Francês",
    "russian": "Russo",
    "portuguese": "Português",
    "turkish": "Turco",
    "greek": "Grego",
    "dutch": "Holandês",
    "italian": "Italiano",
    "chinese": "Chinês",
    "unknown": "Desconhecido",

    "or": "ou",
  "male": "Masculino",
  "female": "Feminino",
  "other": "Outro",
  "language_selected": "{languageName} selecionado",
  "language_changed_to": "Idioma alterado para {languageChangedto}",

  
  "woo_rizz_premium_subscriptions": "✨Assinaturas Premium do Woo Rizz",
  "rizz_subscription_catalog": "Catálogo de assinaturas do Rizz",
  "woo_rizz_offering_subscriptions": "Woo Rizz oferece uma variedade de assinaturas. Compre de acordo com sua escolha e livre-se dos anúncios."



        },
        'tr': {
          // Turkish translations
          
    "drag_drop": "Sürükle ve Bırak veya Bir Resim Seç",
    "paste_message": "Mesajınızı buraya yapıştırın",
    "input_message": "Mesajı girin",
    "submit": "Gönder",
    "response_message": "Yanıt Mesajı",
    "response_of_input": "Girdinizin yanıtı",
    "copied": "Kopyalandı: Yanıt panoya kopyalandı",
    "generate_first_message": "İlk Mesaj",
    "need_assistance": "Yapay Zeka Asistanı",
    "ice_breaker": "Sessizliği Kır",
    "random_response": "Rastgele Oluşturulan Yanıt",
    "response": "Yanıt",
    "random_generator": "Rastgele Üretici",
    "privacy_policy_error": "Gizlilik politikası bağlantısı açılamadı",
    "privacy_policy": "Gizlilik Politikası",
    "play_store_error": "Play Store bağlantısı açılamadı",
    "app_rating": "Uygulama Puanı",
    "google_form_error": "Google Form açılamadı",
    "delete_data_request": "Veri Silme İsteği",
    "vip": "VIP",
    "language": "Dil",
    "no_internet": "İnternet Bağlantısı Yok",
    "connection_lost": "Bağlantınız kesildi. Lütfen internet bağlantınızı kontrol edin ve tekrar deneyin.",
    "okay": "Tamam",
    "retry": "Tekrar Dene",
    "welcome_to_chat_assistant": "Chat Assistant'a Hoşgeldiniz",
    "enter_your_age": "Yaşınızı girin",
    "woo_rizz": "Woo Rizz!",
    "yours_age": "Yaşınız",
    "select_gender": "Cinsiyet Seçin",
    "select_language": "Dil Seçin",
    "lets_start_messaging": "Mesajlaşmaya Başlayalım",
    "ai_assistant_rizz": "AI Yardımcısı Rizz.",
    "current_language": "Geçerli Dil:",

    "english": "İngilizce",
    "arabic": "Arapça",
    "hindi": "Hintçe",
    "spanish": "İspanyolca",
    "german": "Almanca",
    "french": "Fransızca",
    "russian": "Rusça",
    "portuguese": "Portekizce",
    "turkish": "Türkçe",
    "greek": "Yunanca",
    "dutch": "Flemenkçe",
    "italian": "İtalyanca",
    "chinese": "Çince",
    "unknown": "Bilinmeyen",

    "or": "veya",
  "male": "Erkek",
  "female": "Kadın",
  "other": "Diğer",
  "language_selected": "{languageName} seçildi",
  "language_changed_to": "Dil {languageChangedto} olarak değiştirildi",


  "woo_rizz_premium_subscriptions": "✨Woo Rizz Premium Abonelikleri",
  "rizz_subscription_catalog": "Rizz'in Abonelik Kataloğu",
  "woo_rizz_offering_subscriptions": "Woo Rizz, çeşitli abonelikler sunuyor. Kendi seçiminize göre satın alın ve reklamlardan kurtulun."



        },
        'el': {
          // Greek translations
          
    "drag_drop": "Σύρετε και αποθέστε ή επιλέξτε μια εικόνα",
    "paste_message": "Επικολλήστε το μήνυμά σας εδώ",
    "input_message": "Εισαγωγή μηνύματος",
    "submit": "Υποβολή",
    "response_message": "Μήνυμα απάντησης",
    "response_of_input": "Απάντηση στην εισαγωγή σας",
    "copied": "Αντιγράφηκε: Η απάντηση αντιγράφηκε στο πρόχειρο",
    "generate_first_message": "Πρώτο μήνυμα",
    "need_assistance": "Βοηθός Τεχνητής Νοημοσύνης",
    "ice_breaker": "Σπάσε τη σιωπή",
    "random_response": "Τυχαία δημιουργημένη απάντηση",
    "response": "Απάντηση",
    "random_generator": "Τυχαίος Γεννήτορας",
    "privacy_policy_error": "Αποτυχία ανοίγματος συνδέσμου πολιτικής απορρήτου",
    "privacy_policy": "Πολιτική Απορρήτου",
    "play_store_error": "Αποτυχία ανοίγματος συνδέσμου Play Store",
    "app_rating": "Αξιολόγηση Εφαρμογής",
    "google_form_error": "Αποτυχία ανοίγματος Google Form",
    "delete_data_request": "Αίτημα διαγραφής δεδομένων",
    "vip": "VIP",
    "language": "Γλώσσα",
    "no_internet": "Χωρίς σύνδεση στο διαδίκτυο",
    "connection_lost": "Η σύνδεσή σας χάθηκε. Ελέγξτε τη σύνδεση στο διαδίκτυο και προσπαθήστε ξανά.",
    "okay": "Εντάξει",
    "retry": "Δοκιμάστε ξανά",
    "welcome_to_chat_assistant": "Καλώς ήρθατε στο Chat Assistant",
    "enter_your_age": "Εισάγετε την ηλικία σας",
    "woo_rizz": "Woo Rizz!",
    "yours_age": "Η ηλικία σας",
    "select_gender": "Επιλέξτε φύλο",
    "select_language": "Επιλέξτε γλώσσα",
    "lets_start_messaging": "Ας ξεκινήσουμε την αποστολή μηνυμάτων",
    "ai_assistant_rizz": "AI Assistant Rizz.",
    "current_language": "Τρέχουσα γλώσσα:",
    "english": "Αγγλικά",
    "arabic": "Αραβικά",
    "hindi": "Χίντι",
    "spanish": "Ισπανικά",
    "german": "Γερμανικά",
    "french": "Γαλλικά",
    "russian": "Ρωσικά",
    "portuguese": "Πορτογαλικά",
    "turkish": "Τουρκικά",
    "greek": "Ελληνικά",
    "dutch": "Ολλανδικά",
    "italian": "Ιταλικά",
    "chinese": "Κινέζικα",
    "unknown": "Άγνωστο",

    "or": "ή",
  "male": "Άνδρας",
  "female": "Γυναίκα",
  "other": "Άλλο",
  "language_selected": "Επιλέχθηκε {languageName}",
  "language_changed_to": "Η γλώσσα άλλαξε σε {languageChangedto}",


  "woo_rizz_premium_subscriptions": "✨Premium Συνδρομές Woo Rizz",
  "rizz_subscription_catalog": "Κατάλογος Συνδρομών Rizz",
  "woo_rizz_offering_subscriptions": "Το Woo Rizz προσφέρει μια ποικιλία συνδρομών. Αγοράστε σύμφωνα με την επιλογή σας και απαλλαγείτε από τις διαφημίσεις."



        },
        'nl': {
          // Dutch translations
          
    "drag_drop": "Sleep en zet neer of kies een afbeelding",
    "paste_message": "Plak je bericht hier",
    "input_message": "Voer bericht in",
    "submit": "Verzenden",
    "response_message": "Antwoordbericht",
    "response_of_input": "Reactie op je invoer",
    "copied": "Gekopieerd: Antwoord gekopieerd naar het klembord",
    "generate_first_message": "Eerste bericht",
    "need_assistance": "AI-assistent",
    "ice_breaker": "Doorbreek de stilte",
    "random_response": "Willekeurig gegenereerd antwoord",
    "response": "Reactie",
    "random_generator": "Willekeurige generator",
    "privacy_policy_error": "Privacybeleid-link kon niet worden geopend",
    "privacy_policy": "Privacybeleid",
    "play_store_error": "Play Store-link kon niet worden geopend",
    "app_rating": "App-beoordeling",
    "google_form_error": "Google Formulier kon niet worden geopend",
    "delete_data_request": "Verzoek om gegevens te verwijderen",
    "vip": "VIP",
    "language": "Taal",
    "no_internet": "Geen internetverbinding",
    "connection_lost": "Je verbinding is verloren. Controleer je internetverbinding en probeer het opnieuw.",
    "okay": "Oké",
    "retry": "Opnieuw proberen",
    "welcome_to_chat_assistant": "Welkom bij Chat Assistant",
    "enter_your_age": "Voer je leeftijd in",
    "woo_rizz": "Woo Rizz!",
    "yours_age": "Jouw leeftijd",
    "select_gender": "Selecteer geslacht",
    "select_language": "Selecteer taal",
    "lets_start_messaging": "Laten we beginnen met berichten versturen",
    "ai_assistant_rizz": "AI Assistent Rizz.",
    "current_language": "Huidige taal:",

    "english": "Engels",
    "arabic": "Arabisch",
    "hindi": "Hindi",
    "spanish": "Spaans",
    "german": "Duits",
    "french": "Frans",
    "russian": "Russisch",
    "portuguese": "Portugees",
    "turkish": "Turks",
    "greek": "Grieks",
    "dutch": "Nederlands",
    "italian": "Italiaans",
    "chinese": "Chinees",
    "unknown": "Onbekend",

     "or": "of",
  "male": "Man",
  "female": "Vrouw",
  "other": "Anders",
  "language_selected": "{languageName} geselecteerd",
  "language_changed_to": "Taal gewijzigd naar {languageChangedto}",


  "woo_rizz_premium_subscriptions": "✨Woo Rizz Premium-abonnementen",
  "rizz_subscription_catalog": "Rizz's Abonnementencatalogus",
  "woo_rizz_offering_subscriptions": "Woo Rizz biedt een verscheidenheid aan abonnementen. Koop naar eigen keuze en zeg vaarwel tegen advertenties."



        },
        'it': {
          // Italian translations
          
    "drag_drop": "Trascina e rilascia o scegli un'immagine",
    "paste_message": "Incolla il tuo messaggio qui",
    "input_message": "Inserisci messaggio",
    "submit": "Invia",
    "response_message": "Messaggio di risposta",
    "response_of_input": "Risposta al tuo input",
    "copied": "Copiato: Risposta copiata negli appunti",
    "generate_first_message": "Primo messaggio",
    "need_assistance": "Assistente AI",
    "ice_breaker": "Rompi il silenzio",
    "random_response": "Risposta generata casualmente",
    "response": "Risposta",
    "random_generator": "Generatore casuale",
    "privacy_policy_error": "Impossibile aprire il link della privacy policy",
    "privacy_policy": "Privacy Policy",
    "play_store_error": "Impossibile aprire il link di Play Store",
    "app_rating": "Valutazione dell'app",
    "google_form_error": "Impossibile aprire il modulo Google",
    "delete_data_request": "Richiesta di eliminazione dati",
    "vip": "VIP",
    "language": "Lingua",
    "no_internet": "Nessuna connessione a Internet",
    "connection_lost": "La tua connessione è persa. Controlla la tua connessione Internet e riprova.",
    "okay": "Ok",
    "retry": "Riprova",
    "welcome_to_chat_assistant": "Benvenuto in Chat Assistant",
    "enter_your_age": "Inserisci la tua età",
    "woo_rizz": "Woo Rizz!",
    "yours_age": "La tua età",
    "select_gender": "Seleziona genere",
    "select_language": "Seleziona lingua",
    "lets_start_messaging": "Iniziamo a inviare messaggi",
    "ai_assistant_rizz": "AI Assistant Rizz.",
    "current_language": "Lingua attuale:",
    "english": "Inglese",
    "arabic": "Arabo",
    "hindi": "Hindi",
    "spanish": "Spagnolo",
    "german": "Tedesco",
    "french": "Francese",
    "russian": "Russo",
    "portuguese": "Portoghese",
    "turkish": "Turco",
    "greek": "Greco",
    "dutch": "Olandese",
    "italian": "Italiano",
    "chinese": "Cinese",
    "unknown": "Sconosciuto",
    "or": "o",
  "male": "Maschio",
  "female": "Femmina",
  "other": "Altro",
  "language_selected": "{languageName} selezionato",
  "language_changed_to": "Lingua cambiata in {languageChangedto}",

  
  "woo_rizz_premium_subscriptions": "✨Abbonamenti Premium di Woo Rizz",
  "rizz_subscription_catalog": "Catalogo abbonamenti di Rizz",
  "woo_rizz_offering_subscriptions": "Woo Rizz offre una varietà di abbonamenti. Acquista secondo la tua scelta e dì addio agli annunci."



        },
        'zh': {
          // Chinese translations
          
    "drag_drop": "拖放或选择图片",
    "paste_message": "粘贴您的消息",
    "input_message": "输入消息",
    "submit": "提交",
    "response_message": "回复消息",
    "response_of_input": "您的输入的回复",
    "copied": "已复制：回复已复制到剪贴板",
    "generate_first_message": "第一条消息",
    "need_assistance": "AI助手",
    "ice_breaker": "打破沉默",
    "random_response": "随机生成的回复",
    "response": "回复",
    "random_generator": "随机生成器",
    "privacy_policy_error": "无法打开隐私政策链接",
    "privacy_policy": "隐私政策",
    "play_store_error": "无法打开Play商店链接",
    "app_rating": "应用评分",
    "google_form_error": "无法打开Google表单",
    "delete_data_request": "删除数据请求",
    "vip": "VIP",
    "language": "语言",
    "no_internet": "没有互联网连接",
    "connection_lost": "您的连接已丢失。请检查您的互联网连接并重试。",
    "okay": "好的",
    "retry": "重试",
    "welcome_to_chat_assistant": "欢迎使用聊天助手",
    "enter_your_age": "请输入您的年龄",
    "woo_rizz": "赢得Rizz！",
    "yours_age": "您的年龄",
    "select_gender": "选择性别",
    "select_language": "选择语言",
    "lets_start_messaging": "开始发送消息",
    "ai_assistant_rizz": "AI助手Rizz。",
    "current_language": "当前语言：",
    "english": "英语",
    "arabic": "阿拉伯语",
    "hindi": "印地语",
    "spanish": "西班牙语",
    "german": "德语",
    "french": "法语",
    "russian": "俄语",
    "portuguese": "葡萄牙语",
    "turkish": "土耳其语",
    "greek": "希腊语",
    "dutch": "荷兰语",
    "italian": "意大利语",
    "chinese": "中文",
    "unknown": "未知",

     "or": "或",
  "male": "男性",
  "female": "女性",
  "other": "其他",
  "language_selected": "{languageName} 已选择",
  "language_changed_to": "语言更改为 {languageChangedto}",

  
  "woo_rizz_premium_subscriptions": "✨Woo Rizz 高级订阅",
  "rizz_subscription_catalog": "Rizz 的订阅目录",
  "woo_rizz_offering_subscriptions": "Woo Rizz 提供多种订阅选项。根据您的选择购买，并摆脱广告。"



        },

        'id': {
  'drag_drop': 'Seret dan Lepas atau Pilih Gambar',
  'paste_message': 'Tempel Pesan Anda Di Sini',
  'input_message': 'Masukkan Pesan',
  'submit': 'Kirim',
  'response_message': 'Pesan Balasan',
  'response_of_input': 'Balasan dari Masukan Anda',
  'copied': 'Disalin: Balasan disalin ke papan klip',
  'generate_first_message': 'Pesan Pertama',
  'need_assistance': 'Asisten AI',
  'ice_breaker': 'Pecahkan keheningan',
  'random_response': 'Respons yang Dihasilkan Secara Acak',
  'response': 'Balasan',
  'random_generator': 'Penghasil Acak',
  'privacy_policy_error': 'Tidak dapat membuka tautan Kebijakan Privasi',
  'privacy_policy': 'Kebijakan Privasi',
  'play_store_error': 'Tidak dapat membuka tautan Play Store',
  'app_rating': 'Penilaian Aplikasi',
  'google_form_error': 'Tidak dapat membuka Google Formulir',
  'delete_data_request': 'Permintaan Hapus Data',
  'vip': 'VIP',
  'language': 'Bahasa',
  'no_internet': 'Tidak Ada Koneksi Internet',
  'connection_lost': 'Koneksi Anda terputus. Periksa koneksi internet Anda dan coba lagi.',
  'okay': 'Oke',
  'retry': 'Coba Lagi',
  'welcome_to_chat_assistant': 'Selamat Datang di Asisten Obrolan',
  'enter_your_age': 'Masukkan usia Anda',
  'woo_rizz': 'Woo Rizz!',
  'yours_age': 'Usia Anda',
  'select_gender': 'Pilih Jenis Kelamin',
  'select_language': 'Pilih Bahasa',
  'lets_start_messaging': 'Ayo Mulai Mengobrol',
  'ai_assistant_rizz': 'Asisten AI Rizz.',
  'current_language': 'Bahasa Saat Ini:',
  'english': 'Inggris',
  'arabic': 'Arab',
  'hindi': 'Hindi',
  'spanish': 'Spanyol',
  'german': 'Jerman',
  'french': 'Perancis',
  'russian': 'Rusia',
  'portuguese': 'Portugis',
  'turkish': 'Turki',
  'greek': 'Yunani',
  'dutch': 'Belanda',
  'italian': 'Italia',
  'chinese': 'Cina',
  'unknown': 'Tidak Diketahui',
  'or': 'atau',
  'male': 'Pria',
  'female': 'Wanita',
  'other': 'Lainnya',
  'language_selected': '{languageName} dipilih',
  'language_changed_to': 'Bahasa diubah ke {languageChangedto}',
  'woo_rizz_premium_subscriptions': '✨Berlangganan Premium Woo Rizz',
  'rizz_subscription_catalog': 'Katalog Berlangganan Rizz',
  'woo_rizz_offering_subscriptions': 'Woo Rizz menawarkan berbagai langganan. Beli sesuai pilihan Anda dan hilangkan iklan.',
},
'ms': {
  'drag_drop': 'Seret dan Lepas atau Pilih Gambar',
  'paste_message': 'Tampal Mesej Anda Di Sini',
  'input_message': 'Masukkan Mesej',
  'submit': 'Hantar',
  'response_message': 'Mesej Respons',
  'response_of_input': 'Respons untuk Input Anda',
  'copied': 'Disalin: Respons disalin ke papan klip',
  'generate_first_message': 'Mesej Pertama',
  'need_assistance': 'Pembantu AI',
  'ice_breaker': 'Pecahkan Kesunyian',
  'random_response': 'Respons Dihasilkan Secara Rawak',
  'response': 'Respons',
  'random_generator': 'Penjana Rawak',
  'privacy_policy_error': 'Pautan Dasar Privasi tidak dapat dibuka',
  'privacy_policy': 'Dasar Privasi',
  'play_store_error': 'Pautan Play Store tidak dapat dibuka',
  'app_rating': 'Penilaian Aplikasi',
  'google_form_error': 'Google Form tidak dapat dibuka',
  'delete_data_request': 'Permintaan Pemadaman Data',
  'vip': 'VIP',
  'language': 'Bahasa',
  'no_internet': 'Tiada Sambungan Internet',
  'connection_lost': 'Sambungan anda terputus. Sila periksa sambungan internet anda dan cuba lagi.',
  'okay': 'Baik',
  'retry': 'Cuba Lagi',
  'welcome_to_chat_assistant': 'Selamat Datang ke Pembantu Sembang',
  'enter_your_age': 'Masukkan Umur Anda',
  'woo_rizz': 'Woo Rizz!',
  'yours_age': 'Umur Anda',
  'select_gender': 'Pilih Jantina',
  'select_language': 'Pilih Bahasa',
  'lets_start_messaging': 'Mari Mulakan Bersembang',
  'ai_assistant_rizz': 'Pembantu AI Rizz.',
  'current_language': 'Bahasa Semasa:',
  'english': 'Bahasa Inggeris',
  'arabic': 'Bahasa Arab',
  'hindi': 'Bahasa Hindi',
  'spanish': 'Bahasa Sepanyol',
  'german': 'Bahasa Jerman',
  'french': 'Bahasa Perancis',
  'russian': 'Bahasa Rusia',
  'portuguese': 'Bahasa Portugis',
  'turkish': 'Bahasa Turki',
  'greek': 'Bahasa Yunani',
  'dutch': 'Bahasa Belanda',
  'italian': 'Bahasa Itali',
  'chinese': 'Bahasa Cina',
  'unknown': 'Tidak Diketahui',
  'or': 'atau',
  'male': 'Lelaki',
  'female': 'Perempuan',
  'other': 'Lain-lain',
  'language_selected': '{languageName} dipilih',
  'language_changed_to': 'Bahasa ditukar kepada {languageChangedto}',
  'woo_rizz_premium_subscriptions': '✨Langganan Premium Woo Rizz',
  'rizz_subscription_catalog': 'Katalog Langganan Rizz',
  'woo_rizz_offering_subscriptions': 'Woo Rizz menawarkan pelbagai langganan. Beli mengikut pilihan anda dan hapuskan iklan.',
},

'fil': {
  'drag_drop': 'I-drag at I-drop o Pumili ng Larawan',
  'paste_message': 'I-paste ang Mensahe Dito',
  'input_message': 'Ilagay ang Mensahe',
  'submit': 'Ipasa',
  'response_message': 'Mensahe ng Tugon',
  'response_of_input': 'Tugon sa Iyong Input',
  'copied': 'Nakopya: Tugon nakopya sa clipboard',
  'generate_first_message': 'Unang Mensahe',
  'need_assistance': 'AI Katulong',
  'ice_breaker': 'Basagin ang Katahimikan',
  'random_response': 'Random na Tugon',
  'response': 'Tugon',
  'random_generator': 'Random na Generator',
  'privacy_policy_error': 'Hindi mabuksan ang link ng Patakaran sa Privacy',
  'privacy_policy': 'Patakaran sa Privacy',
  'play_store_error': 'Hindi mabuksan ang link ng Play Store',
  'app_rating': 'Rating ng App',
  'google_form_error': 'Hindi mabuksan ang Google Form',
  'delete_data_request': 'Kahilingan sa Pag-delete ng Data',
  'vip': 'VIP',
  'language': 'Wika',
  'no_internet': 'Walang Internet na Koneksyon',
  'connection_lost': 'Nawala ang koneksyon mo. Paki-check ang internet mo at subukan ulit.',
  'okay': 'Sige',
  'retry': 'Subukang Muli',
  'welcome_to_chat_assistant': 'Maligayang Pagdating sa Chat Assistant',
  'enter_your_age': 'Ilagay ang Iyong Edad',
  'woo_rizz': 'Woo Rizz!',
  'yours_age': 'Edad Mo',
  'select_gender': 'Pumili ng Kasarian',
  'select_language': 'Pumili ng Wika',
  'lets_start_messaging': 'Simulan Natin ang Pakikipag-chat',
  'ai_assistant_rizz': 'AI Katulong Rizz.',
  'current_language': 'Kasalukuyang Wika:',
  'english': 'Ingles',
  'arabic': 'Arabe',
  'hindi': 'Hindi',
  'spanish': 'Espanyol',
  'german': 'Aleman',
  'french': 'Pranses',
  'russian': 'Ruso',
  'portuguese': 'Portuges',
  'turkish': 'Turko',
  'greek': 'Griyego',
  'dutch': 'Olandes',
  'italian': 'Italyano',
  'chinese': 'Tsino',
  'unknown': 'Hindi Alam',
  'or': 'o',
  'male': 'Lalaki',
  'female': 'Babae',
  'other': 'Iba pa',
  'language_selected': '{languageName} napili',
  'language_changed_to': 'Ang wika ay binago sa {languageChangedto}',
  'woo_rizz_premium_subscriptions': '✨Woo Rizz Premium Subscriptions',
  'rizz_subscription_catalog': 'Katalogo ng Subskripsyon ni Rizz',
  'woo_rizz_offering_subscriptions': 'Nag-aalok ang Woo Rizz ng iba’t ibang subskripsyon. Bumili ayon sa iyong kagustuhan at alisin ang mga ad.',
},
'ja': {
  'drag_drop': 'ドラッグ＆ドロップまたは画像を選択',
  'paste_message': 'ここにメッセージを貼り付けてください',
  'input_message': 'メッセージを入力',
  'submit': '送信',
  'response_message': '応答メッセージ',
  'response_of_input': '入力への応答',
  'copied': 'コピー済み: 応答がクリップボードにコピーされました',
  'generate_first_message': '最初のメッセージ',
  'need_assistance': 'AIアシスタント',
  'ice_breaker': '沈黙を破る',
  'random_response': 'ランダムに生成された応答',
  'response': '応答',
  'random_generator': 'ランダムジェネレーター',
  'privacy_policy_error': 'プライバシーポリシーのリンクを開けませんでした',
  'privacy_policy': 'プライバシーポリシー',
  'play_store_error': 'Playストアのリンクを開けませんでした',
  'app_rating': 'アプリの評価',
  'google_form_error': 'Googleフォームを開けませんでした',
  'delete_data_request': 'データ削除リクエスト',
  'vip': 'VIP',
  'language': '言語',
  'no_internet': 'インターネット接続がありません',
  'connection_lost': '接続が失われました。インターネット接続を確認して、もう一度お試しください。',
  'okay': 'OK',
  'retry': '再試行',
  'welcome_to_chat_assistant': 'チャットアシスタントへようこそ',
  'enter_your_age': 'あなたの年齢を入力してください',
  'woo_rizz': 'Woo Rizz!',
  'yours_age': 'あなたの年齢',
  'select_gender': '性別を選択',
  'select_language': '言語を選択',
  'lets_start_messaging': 'メッセージングを始めましょう',
  'ai_assistant_rizz': 'AIアシスタントRizz。',
  'current_language': '現在の言語:',
  'english': '英語',
  'arabic': 'アラビア語',
  'hindi': 'ヒンディー語',
  'spanish': 'スペイン語',
  'german': 'ドイツ語',
  'french': 'フランス語',
  'russian': 'ロシア語',
  'portuguese': 'ポルトガル語',
  'turkish': 'トルコ語',
  'greek': 'ギリシャ語',
  'dutch': 'オランダ語',
  'italian': 'イタリア語',
  'chinese': '中国語',
  'unknown': '不明',
  'or': 'または',
  'male': '男性',
  'female': '女性',
  'other': 'その他',
  'language_selected': '{languageName}を選択',
  'language_changed_to': '言語が{languageChangedto}に変更されました',
  'woo_rizz_premium_subscriptions': '✨Woo Rizzプレミアムサブスクリプション',
  'rizz_subscription_catalog': 'Rizzのサブスクリプションカタログ',
  'woo_rizz_offering_subscriptions': 'Woo Rizzはさまざまなサブスクリプションを提供しています。好みに応じて購入し、広告を排除しましょう。',
},
'pl': {
  'drag_drop': 'Przeciągnij i Upuść lub Wybierz Obraz',
  'paste_message': 'Wklej swoją wiadomość tutaj',
  'input_message': 'Wprowadź wiadomość',
  'submit': 'Wyślij',
  'response_message': 'Wiadomość zwrotna',
  'response_of_input': 'Odpowiedź na Twoje dane wejściowe',
  'copied': 'Skopiowano: Odpowiedź skopiowana do schowka',
  'generate_first_message': 'Pierwsza wiadomość',
  'need_assistance': 'Asystent AI',
  'ice_breaker': 'Przełam ciszę',
  'random_response': 'Losowo wygenerowana odpowiedź',
  'response': 'Odpowiedź',
  'random_generator': 'Generator losowy',
  'privacy_policy_error': 'Nie udało się otworzyć linku do Polityki prywatności',
  'privacy_policy': 'Polityka prywatności',
  'play_store_error': 'Nie udało się otworzyć linku do Sklepu Play',
  'app_rating': 'Ocena aplikacji',
  'google_form_error': 'Nie udało się otworzyć Google Formularza',
  'delete_data_request': 'Żądanie usunięcia danych',
  'vip': 'VIP',
  'language': 'Język',
  'no_internet': 'Brak połączenia z Internetem',
  'connection_lost': 'Twoje połączenie zostało utracone. Sprawdź swoje połączenie z Internetem i spróbuj ponownie.',
  'okay': 'OK',
  'retry': 'Ponów',
  'welcome_to_chat_assistant': 'Witamy w Asystencie czatu',
  'enter_your_age': 'Wprowadź swój wiek',
  'woo_rizz': 'Woo Rizz!',
  'yours_age': 'Twój wiek',
  'select_gender': 'Wybierz płeć',
  'select_language': 'Wybierz język',
  'lets_start_messaging': 'Zacznijmy rozmawiać',
  'ai_assistant_rizz': 'Asystent AI Rizz.',
  'current_language': 'Aktualny język:',
  'english': 'Angielski',
  'arabic': 'Arabski',
  'hindi': 'Hindi',
  'spanish': 'Hiszpański',
  'german': 'Niemiecki',
  'french': 'Francuski',
  'russian': 'Rosyjski',
  'portuguese': 'Portugalski',
  'turkish': 'Turecki',
  'greek': 'Grecki',
  'dutch': 'Niderlandzki',
  'italian': 'Włoski',
  'chinese': 'Chiński',
  'unknown': 'Nieznany',
  'or': 'lub',
  'male': 'Mężczyzna',
  'female': 'Kobieta',
  'other': 'Inne',
  'language_selected': 'Wybrano {languageName}',
  'language_changed_to': 'Język zmieniono na {languageChangedto}',
},
'ko': {
  'drag_drop': '드래그 앤 드롭 또는 이미지 선택',
  'paste_message': '여기에 메시지를 붙여넣으세요',
  'input_message': '메시지를 입력하세요',
  'submit': '제출',
  'response_message': '응답 메시지',
  'response_of_input': '입력에 대한 응답',
  'copied': '복사됨: 응답이 클립보드에 복사되었습니다',
  'generate_first_message': '첫 번째 메시지 생성',
  'need_assistance': 'AI 도우미',
  'ice_breaker': '어색한 분위기 깨기',
  'random_response': '랜덤으로 생성된 응답',
  'response': '응답',
  'random_generator': '랜덤 생성기',
  'privacy_policy_error': '개인정보 처리방침 링크를 열 수 없습니다',
  'privacy_policy': '개인정보 처리방침',
  'play_store_error': '플레이 스토어 링크를 열 수 없습니다',
  'app_rating': '앱 평가',
  'google_form_error': 'Google 양식을 열 수 없습니다',
  'delete_data_request': '데이터 삭제 요청',
  'vip': 'VIP',
  'language': '언어',
  'no_internet': '인터넷 연결 없음',
  'connection_lost': '연결이 끊어졌습니다. 인터넷 연결을 확인하고 다시 시도하세요.',
  'okay': '확인',
  'retry': '재시도',
  'welcome_to_chat_assistant': '채팅 도우미에 오신 것을 환영합니다',
  'enter_your_age': '나이를 입력하세요',
  'woo_rizz': 'Woo Rizz!',
  'yours_age': '당신의 나이',
  'select_gender': '성별을 선택하세요',
  'select_language': '언어를 선택하세요',
  'lets_start_messaging': '메시지 시작하기',
  'ai_assistant_rizz': 'AI 도우미 Rizz.',
  'current_language': '현재 언어:',
  'english': '영어',
  'arabic': '아랍어',
  'hindi': '힌디어',
  'spanish': '스페인어',
  'german': '독일어',
  'french': '프랑스어',
  'russian': '러시아어',
  'portuguese': '포르투갈어',
  'turkish': '터키어',
  'greek': '그리스어',
  'dutch': '네덜란드어',
  'italian': '이탈리아어',
  'chinese': '중국어',
  'unknown': '알 수 없음',
  'or': '또는',
  'male': '남성',
  'female': '여성',
  'other': '기타',
  'language_selected': '{languageName} 선택됨',
  'language_changed_to': '언어가 {languageChangedto}(으)로 변경되었습니다',
  'woo_rizz_premium_subscriptions': '✨Woo Rizz 프리미엄 구독',
  'rizz_subscription_catalog': 'Rizz 구독 카탈로그',
  'woo_rizz_offering_subscriptions': 'Woo Rizz는 다양한 구독 옵션을 제공합니다. 광고를 제거하려면 선호하는 구독을 구매하세요.',
},
'vi': {
  'drag_drop': 'Kéo và Thả hoặc Chọn Hình ảnh',
  'paste_message': 'Dán tin nhắn của bạn tại đây',
  'input_message': 'Nhập tin nhắn',
  'submit': 'Gửi',
  'response_message': 'Tin nhắn phản hồi',
  'response_of_input': 'Phản hồi từ đầu vào của bạn',
  'copied': 'Đã sao chép: Phản hồi đã được sao chép vào clipboard',
  'generate_first_message': 'Tin nhắn đầu tiên',
  'need_assistance': 'Trợ lý AI',
  'ice_breaker': 'Phá vỡ sự im lặng',
  'random_response': 'Phản hồi được tạo ngẫu nhiên',
  'response': 'Phản hồi',
  'random_generator': 'Trình tạo ngẫu nhiên',
  'privacy_policy_error': 'Không thể mở liên kết Chính sách quyền riêng tư',
  'privacy_policy': 'Chính sách quyền riêng tư',
  'play_store_error': 'Không thể mở liên kết Cửa hàng Play',
  'app_rating': 'Đánh giá Ứng dụng',
  'google_form_error': 'Không thể mở Google Form',
  'delete_data_request': 'Yêu cầu xóa dữ liệu',
  'vip': 'VIP',
  'language': 'Ngôn ngữ',
  'no_internet': 'Không có kết nối Internet',
  'connection_lost': 'Kết nối của bạn đã bị mất. Kiểm tra kết nối Internet của bạn và thử lại.',
  'okay': 'Đồng ý',
  'retry': 'Thử lại',
  'welcome_to_chat_assistant': 'Chào mừng đến với Trợ lý Trò chuyện',
  'enter_your_age': 'Nhập tuổi của bạn',
  'woo_rizz': 'Woo Rizz!',
  'yours_age': 'Tuổi của bạn',
  'select_gender': 'Chọn giới tính',
  'select_language': 'Chọn ngôn ngữ',
  'lets_start_messaging': 'Hãy bắt đầu nhắn tin',
  'ai_assistant_rizz': 'Trợ lý AI Rizz.',
  'current_language': 'Ngôn ngữ hiện tại:',
  'english': 'Tiếng Anh',
  'arabic': 'Tiếng Ả Rập',
  'hindi': 'Tiếng Hindi',
  'spanish': 'Tiếng Tây Ban Nha',
  'german': 'Tiếng Đức',
  'french': 'Tiếng Pháp',
  'russian': 'Tiếng Nga',
  'portuguese': 'Tiếng Bồ Đào Nha',
  'turkish': 'Tiếng Thổ Nhĩ Kỳ',
  'greek': 'Tiếng Hy Lạp',
  'dutch': 'Tiếng Hà Lan',
  'italian': 'Tiếng Ý',
  'chinese': 'Tiếng Trung',
  'unknown': 'Không xác định',
  'or': 'hoặc',
  'male': 'Nam',
  'female': 'Nữ',
  'other': 'Khác',
  'language_selected': '{languageName} được chọn',
  'language_changed_to': 'Ngôn ngữ đã thay đổi thành {languageChangedto}',
  'woo_rizz_premium_subscriptions': '✨Đăng ký Woo Rizz Cao cấp',
  'rizz_subscription_catalog': 'Danh mục đăng ký của Rizz',
  'woo_rizz_offering_subscriptions': 'Woo Rizz cung cấp nhiều gói đăng ký. Mua theo ý thích của bạn và loại bỏ quảng cáo.',
},

      };

      
}
